#include "__cf_mainModel_matlab2013b_working_attitude.h"
#ifndef RTW_HEADER_mainModel_matlab2013b_working_attitude_capi_h
#define RTW_HEADER_mainModel_matlab2013b_working_attitude_capi_h
#include "mainModel_matlab2013b_working_attitude.h"
extern void mainModel_matlab2013b_working_attitude_InitializeDataMapInfo ( )
;
#endif
